return empty vol map if /dev/disk/by-id not there
thecodeteam/libstorage pull request #469
Opened 2017-03-16 21:44 UTC by codenrhoden

Fixes #466

2017-03-22 19:05 UTC, akutz commented on drivers/storage/scaleio/executor/scaleio_executor.go
> +		if os.IsNotExist(err) {
Hi @codenrhoden,

Be aware of the [tricky nature](http://stackoverflow.com/questions/12518876/how-to-check-if-a-file-exists-in-go/22467409#22467409) of `os.IsNotExist`. The Gotil package has a function named [`FileExists`](https://github.com/akutz/gotil/blob/master/gotil.go#L155-L161) that already handles this.

2017-03-22 19:05 UTC, akutz requested changes

2017-03-22 19:05 UTC, akutz commented on drivers/storage/scaleio/executor/scaleio_executor.go
> +		if os.IsNotExist(err) {
Hi @codenrhoden,

Be aware of the [tricky nature](http://stackoverflow.com/questions/12518876/how-to-check-if-a-file-exists-in-go/22467409#22467409) of `os.IsNotExist`. The Gotil package has a function named [`FileExists`](https://github.com/akutz/gotil/blob/master/gotil.go#L155-L161) that already handles this.

2017-03-23 17:38 UTC, codenrhoden commented
@akutz. Thanks for the heads up. not sure why I didn't use `gotil.FileExists()`, as I have used it before...

I guess because I was of the mindset to check what the error was, rather than checking if the dir exists _first_. Take another look when you can!

2017-03-23 18:13 UTC, akutz approved these changes

2017-03-23 18:13 UTC, akutz commented
Hi @codenrhoden,

Mind rebasing this onto `master`? I can merge anyway, but since I know you're online, I prefer rebase when possible.

2017-03-23 18:48 UTC, codenrhoden commented
@akutz I always prefer rebase as well. Should be good to go!

2017-03-23 18:56 UTC, merged