libStorage Token Support (JWT)
thecodeteam/libstorage pull request #501
Opened 2017-04-05 00:36 UTC by akutz

This patch introduces support for JSON Web Tokens, used to restrict access to API resources to clients that provide valid tokens with sufficient claims. Please see the commit's doc section for additional information.

2017-04-05 19:22 UTC, codenrhoden commented on .docs/user-guide/config.md
> +`libstorage.server.auth`. This property contains three child properties:
s/three/five/

2017-04-05 19:46 UTC, codenrhoden commented on api/server/security/security_token.go
> +	for _, v := range config.Deny {
This code that loops through Denied and Allow subjects identical to that found in the service auth handler (when a previously validated token is already in the context). Could we move this bit of logic in a common function, such as `security.ValidateTokenSubject(config, tok.Subject)` and call that from both places?

2017-04-05 20:09 UTC, codenrhoden requested changes
This is looking good. Apologies that two of my review comments went out as single comments rather than all at once in single review!

I know you noted this already, but just for posterity there is not any logic in place that would return an HTTP 401 error if you do an API call on multiple services w/o the JWT and one of the services requires it.

2017-04-05 20:09 UTC, codenrhoden commented on api/types/types_errors.go
> +var ErrMissingStorageService = errors.New("missing storage service")
Why the use of `errors` instead of `goof` here? This one is defined differently than `ErroTimedOut` and `ErrNotImplemented`

2017-04-06 18:08 UTC, akutz commented on api/types/types_errors.go
> +var ErrMissingStorageService = errors.New("missing storage service")
Hi @codenrhoden,

This has been handled.

2017-04-06 18:16 UTC, akutz commented
Hi @codenrhoden,

FYI there *is* now logic to handle the multi-service auth. I created a new handler at [`handlers_auth_all_services.go`](https://github.com/akutz/libstorage/blob/feature/token-support/api/server/handlers/handlers_auth_all_services.go) that is applied to the following routes:

* `/services/`
* `/volumes/`
* `/snapshots/`

The latest update also handles the duplicate code we discussed. Thank you again for providing such a comprehensive review.

2017-04-06 18:16 UTC, codenrhoden approved these changes

2017-04-06 20:15 UTC, merged